apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres_ds
    type: postgres
    access: proxy
    url: postgres:5432
    database: equity_researcher
    user: equity
    isDefault: true
    editable: false
    secureJsonData:
      password: equity
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
